// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhfvyxzsxzpkxzskrtdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oZnZ5eHpzeHpwa3h6c2tydGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTY1MjMsImV4cCI6MjA2NjQzMjUyM30.6LKHcmYuIlXOkFYLK3pWHYlUhVd2EOly1ZZIQxPQpVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);